"""empty message

Revision ID: 07dc492f2dff
Revises: b3a32cd1e077
Create Date: 2023-11-15 13:48:24.709408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '07dc492f2dff'
down_revision = '6090b2341b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formatted_phone_number', sa.String(length=20), nullable=True),
    sa.Column('name', mssql.NVARCHAR(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', mssql.NVARCHAR(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', mssql.NVARCHAR(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('translated', sa.Boolean(), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=255), nullable=True),
    sa.Column('relative_time_description', sa.String(length=50), nullable=True),
    sa.Column('author_url', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('place')
    # ### end Alembic commands ###
