"""empty message

Revision ID: 6090b2341b49
Revises: b3a32cd1e077
Create Date: 2023-10-31 20:29:24.030004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '6090b2341b49'
down_revision = 'b3a32cd1e077'
branch_labels = None
depends_on = None


def upgrade():
   pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=mssql.REAL(),
               existing_nullable=False)


    # ### end Alembic commands ###
