"""empty message

Revision ID: a8a22e695365
Revises: fa8d2d48cc51
Create Date: 2023-11-15 16:08:18.915542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a8a22e695365'
down_revision = 'fa8d2d48cc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=mssql.REAL(),
    #            type_=sa.Float(precision=2),
    #            existing_nullable=False)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.Float(precision=2),
    #            type_=mssql.REAL(),
    #            existing_nullable=False)
    pass
    # ### end Alembic commands ###
