"""empty message

Revision ID: b3a32cd1e077
Revises: c5e7aad121ad
Create Date: 2023-10-30 17:39:40.740590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a32cd1e077'
down_revision = 'c5e7aad121ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.create_table('keyterms_selected',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('text', sa.String(length=80), nullable=False),
    # sa.Column('keyterms', sa.String(length=2000), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('keyterms_selected')
    pass
    # ### end Alembic commands ###
