"""empty message

Revision ID: fa8d2d48cc51
Revises: 07dc492f2dff
Create Date: 2023-11-15 16:02:27.060589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'fa8d2d48cc51'
down_revision = '07dc492f2dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_column('place_id')

        # ### end Alembic commands ###
